Repository helix-datasets/helix, pull requests merged in 2024-06, with the labels that each got.

#28 chore: update dependencies and supported python versions
  .github/workflows/pull-request.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  helix/management/commands/list.py
  helix/utils.py
  setup.py
Labels: infrastructure

#27 Helix documentation fixes
  docs/tutorial/writing-your-first-component.rst
Labels: documentation

#29 chore: add required readthedocs config file
  .readthedocs.yaml
Labels: documentation, infrastructure

#30 chore: fix readthedocs build dependencies
  .readthedocs.yaml
Labels: documentation, infrastructure
